// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcIAAfJILxQlehoDz28WVE3RwMKe76EYM',
    appId: '1:392536993196:android:ba7d8c20d0371003005e09',
    messagingSenderId: '392536993196',
    projectId: 'lp4appusuarios',
    storageBucket: 'lp4appusuarios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmyYU7LglLAr15BiogKEjaOrQPrh4Gacw',
    appId: '1:392536993196:ios:b2b0ff695cdf8387005e09',
    messagingSenderId: '392536993196',
    projectId: 'lp4appusuarios',
    storageBucket: 'lp4appusuarios.appspot.com',
    iosClientId: '392536993196-k0e5ufglj7tlq2q650atj1il8gm4riqi.apps.googleusercontent.com',
    iosBundleId: '4',
  );
}
